import type { Metadata } from "next";
import { Inter, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-context";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
  display: "swap",
});

const siteUrl = process.env.NEXT_PUBLIC_APP_URL || "https://fielchat.com";

export const metadata: Metadata = {
  title: "FIEL.IA - O Assistente do Torcedor Corinthiano",
  description: "Quizzes semanais com prêmios reais, notícias verificadas e assistente inteligente no WhatsApp para a Fiel Torcida. Chat com IA especialista no Corinthians 24/7.",
  keywords: ["Corinthians", "SCCP", "Fiel", "Quiz", "Notícias", "WhatsApp", "IA", "Inteligência Artificial", "Torcedor", "Timão"],
  authors: [{ name: "FIEL.IA" }],
  metadataBase: new URL(siteUrl),
  openGraph: {
    title: "FIEL.IA - O Assistente do Torcedor Corinthiano",
    description: "Chat com IA especialista no Timão. Notícias verificadas. Quiz com prêmios reais. Tudo no site e WhatsApp.",
    type: "website",
    locale: "pt_BR",
    url: siteUrl,
    siteName: "FIEL.IA",
    // OG image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "FIEL.IA - O Assistente do Torcedor Corinthiano",
    description: "Chat com IA especialista no Timão. Quiz com prêmios reais. Notícias verificadas.",
    // OG image is auto-generated by app/opengraph-image.tsx
  },
  icons: {
    icon: "/favicon.ico",
  },
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark" suppressHydrationWarning>
      <body className={`${inter.variable} ${bebas.variable} antialiased`}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
