ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "cpfHash" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "freeRegisteredAt" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "termsAcceptedAt" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "termsVersion" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "funnelSource" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "funnelStage" TEXT NOT NULL DEFAULT 'new';

CREATE UNIQUE INDEX IF NOT EXISTS "users_cpfHash_key" ON "users"("cpfHash");
